### ISSUE TITLE
Email not in Database?

### ISSUE THREAD

**Issue by jcleaves** [fridgecow/smartalarm#5] opened 2018-02-01 19:05 UTC
I haven't seen anything reported on this, so I hope I'm not duplicating a bug report here.

I'm trying to export my data, but it's saying my 'Email address not in database'.  I've added my Gmail address to the Settings and signed up as a beta user.

Running on an LG R with AW2.  Nothing fancy, no hacks, non-rooted.

**Comment by fridgecow** [comment] 2018-02-01 21:37
There have been issues with emails recently, but I think people starting the onboarding process today should be okay.

What happened: sometime in the early morning of Feb 1, my web server started _seriously_ delaying outgoing email, and potentially even dropping messages. I only discovered this when I woke up, and then changed over to using the gmail API to send emails from smartalarm@fridgecow.com (which, quite frankly, is better anyway).

This left quite a few hours during which emails just weren't working - and then a few more hours where they weren't working perfectly because of my hurry to replace the old system.

@jcleaves, whether due to this, or an unrelated issue (watch connectivity, etc), your confirmation email was dropped. Please try clearing your email in the preferences, tapping "Done" to save that change, then re-entering your email.

In the next release, and already implemented in my testing version, is a "Resend confirmation email" button.

Let me know if that's worked so I can decide what to do with this issue.

**Comment by jcleaves** [comment] 2018-02-01 21:48
Deleted, and re-entered my address.  "Confirmation Email Sent".  Waiting on that, but this is farther than I was getting before.

**Comment by fridgecow** [comment] 2018-02-01 22:12
You should have received the email by now - any luck?

**Comment by jcleaves** [comment] 2018-02-01 22:14
Nice timing.  I just posted an edit.  But still no email.

**Comment by fridgecow** [comment] 2018-02-01 22:21
From my end everything looks good. You're in the database, as unconfirmed, and the confirmation email appears to have sent (in fact, it should have sent from the moment 'Confirmation Email Sent' was shown :/)

Make sure you're checking your spam, I suppose.

I'm also going to manually confirm you, but let me know if/when the email comes through - and also if subsequent emails work.

**Comment by jcleaves** [comment] 2018-02-01 22:30
Thanks for that. Still no confirmation, but it does say "Export Success"
now. Waiting for the CSV.

**Comment by jcleaves** [comment] 2018-02-01 22:37
Can you send a test message from a different server to that email to verify all the simple things? Typos, abbreviated variables, etc.

**Comment by jcleaves** [comment] 2018-02-01 22:37
BTW: Nothing from you in SPAM or Junk.

**Comment by fridgecow** [comment] 2018-02-01 23:04
I believe I may have been running into the gmail sending quotas. I've
reverted back to an old version of the email server, which is sad but seems
to be working (again...)

**Comment by jcleaves** [comment] 2018-02-01 23:11
Oh. How many emails are you sending? I thought that was a pretty high quota.

I'll let you know if anything comes in. Do I need to export again?

**Comment by fridgecow** [comment] 2018-02-01 23:13
Yeah, you'll need to export again.

The API's quota is plenty high - however, the quota for gmail *accounts *is
much lower. Normally, API usage is spread across multiple accounts!

**Comment by jcleaves** [comment] 2018-02-01 23:13
Never mind. I did. And it just came in.

**Comment by fridgecow** [comment] 2018-02-01 23:19
Cool, I'll close this - but I imagine this won't be the end of the email issues!

Status: solved

**Closed by fridgecow** 2018-02-01 23:19 UTC

**Comment by jcleaves** [comment] 2018-02-01 23:33
Confirmation email came in 11 minutes ago.

**Comment by fridgecow** [comment] 2018-02-01 23:35
You're kidding me.

Ugh, who knows any more.

**Comment by jcleaves** [comment] 2018-02-02 00:04
And now I'm getting more Sleep Summaries.The queue is letting loose. Lol

**Comment by fridgecow** [comment] 2018-02-02 00:13
I'm going to look into a more long term, possible paid solution. #6

**Comment by jcleaves** [comment] 2018-02-02 00:45
How about this.  If you're only supporting AW2, use the Gmail account on
the watch to have it email themselves.  Or upload to their Google account?
Both are free and remove the server cost for you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by fridgecow** [comment] 2018-02-02 10:50
That's a nice solution - but is it possible to have an AW2 watch without a google sign in? I'm not sure.
